---
  language: python
  os: linux
  dist: bionic
  
  env:
    - ROLE_NAME=prometheus_speedtest
  
  install:
    # Install ansible
    - pip install ansible
    # Check ansible version
    - ansible --version
  
  before_script:
    # Rename project dir to actual role name
    - cd ../
    - mv ansible-role-$ROLE_NAME dmaes.$ROLE_NAME
    - cd dmaes.$ROLE_NAME
    # Create ansible.cfg with correct roles_path
    - printf '[defaults]\nroles_path=../' >ansible.cfg
  
  script:
    # Basic role syntax check
    - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  
  notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/