- name: Ensure prometheus_speedtest group
  group:
    name: "{{ prometheus_speedtest_group }}"
    system: yes
    state: present
  when: prometheus_speedtest_group != 'root'

- name: Ensure prometheus_speedtest user
  user:
    name: "{{ prometheus_speedtest_user }}"
    group: "{{ prometheus_speedtest_group }}"
    shell: /usr/sbin/nologin
    system: yes
    home: "{{ _prometheus_speedtest_virtualenv }}"
    create_home: no
    state: present
  when: prometheus_speedtest_user != 'root'

- name: Install prometheus_speedtest
  pip:
    name: prometheus_speedtest
    version: "{{ prometheus_speedtest_version }}"
    virtualenv: "{{ _prometheus_speedtest_virtualenv }}"
    virtualenv_python: python3.7

- name: Install binary
  template:
    src: prometheus_speedtest.sh.j2
    dest: "{{ _prometheus_speedtest_binary_directory }}/prometheus_speedtest"
    mode: u=rwx,go=rx