- import_tasks: install.yml
  become: true
  tags:
    - prometheus_speedtest_install

- import_tasks: configure.yml
  become: true
  tags:
    - prometheus_speedtest_configure

- name: Ensure prometheus_speedtest started and enabled
  systemd:
    name: prometheus_speedtest
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - prometheus_speedtest_run